[DR-3393] [DR-3391] [DR-3385] Upgrade Spring 2.7.4 -> 3.1.6, TCL 0.0.75 -> 0.1.9 (#97)
* DR-3393 Upgrade Spring 2.7.4 -> 3.1.2, TCL 0.0.75 -> 0.1.7

Which upgrades transitive deps needed to resolve security tickets DR-3385, DR-3391
(and remove previous version pins for past security upgrades).

* In Spring 3, javax -> jakarta

* Migrate Apache HttpClient 4->5

Using https://hc.apache.org/httpcomponents-client-5.3.x/migration-guide/preparation.html as a helper.
Most old interfaces / classes resolved automatically after swapping org.apache.http imports with org.apache.hc.httpclient5, but SSL settings required extra attention.
We now set the SSL socket factory on the PoolingConnectionManager which is passed to our CloseableHttpClient.

* Logback >1.3 no longer allows nesting if elts within appender, logger, root elts

Fixed our configuration according to their guide: https://logback.qos.ch/codes.html#nested_if_element

* Needed OTEL set-up for DrsHub to start

Looking at recent PRs for other services who also added these imports and similar config

* Spotbugs NP_NULL_PARAM_DEREF

I don't think that Spotbugs is being very smart here: DrsMetadata.Builder() can accept a null DrsResponse, but there's no harm in moving our call to the setter within our existing null check.

* Disable OTEL in tests

Without this, tests extending BaseTest were failing with errors like:
Invalid bean definition with name 'otelWebMvcFilter' defined in class path resource

* DR-3385 CVE-2023-6378 Upgrade logback-classic, logback-core to 1.4.14

It was not enough that we updated TCL, since we exclude its spring dependency.
Spring boot hasn't yet upgraded its logback versions, so for the time being we can pull in non-vulnerable versions ourselves.
Added a note to check back on this following the next Spring boot release.

While here, realized that I wasn't pulling in the latest 3.1.x Spring boot version, so brought it up to 3.1.6.

* Delegate Spring Boot dependency management to plugin

Upgraded io.spring.dependency-management plugin to the latest version.
Happily, we now only set our Spring Boot version in one place.

* Gradle convention: only use double quotes for interpolated strings

* Update GlobalExceptionHandler.buildErrorReport signature

This simplifies our call to it.

* Upgrade Sam client library to get Jakarta client

While here, upgraded to latest TCL and ECM Client...
But sadly, ECM does not currently publish a Jakarta client.
Until they do, DrsHub cannot upgrade to Spring 3.
Right now, I suspect this incompatibility is driving errors like the following when attempting to fetch a user's passport from ECM:

Caused by: java.lang.NoSuchMethodError: 'org.springframework.http.HttpStatus org.springframework.http.ResponseEntity.getStatusCode()'
        at bio.terra.externalcreds.client.ApiClient.invokeAPI(ApiClient.java:500)
        at bio.terra.externalcreds.api.OidcApi.getProviderPassportWithHttpInfo(OidcApi.java:314)

* Use new Jakarta-based ECM client library

Added in https://github.com/DataBiosphere/terra-external-credentials-manager/pull/160

* Update google dependencies

Where possible, allow dependencies to get their versions from the parent libraries-bom
Found that org.springframework.cloud:spring-cloud-gcp-starter-logging has been usurped by a dep of the same name in com.google.cloud

* Upgrade OTEL, correct its configuration

* Pull in new ECM Jakarta-based library

Created now that ECM is fully on Spring 3 in https://github.com/DataBiosphere/terra-external-credentials-manager/pull/161

* Designate this release as #major

While DrsHub does not publish a client library, the significance of these upgrades warrants a major version bump rather than the usual minor version bump.

* Swagger UI drive-by config: show request duration, enable 'try it out' by default