Upgrade Sam client library to get Jakarta client
While here, upgraded to latest TCL and ECM Client...
But sadly, ECM does not currently publish a Jakarta client.
Until they do, DrsHub cannot upgrade to Spring 3.
Right now, I suspect this incompatibility is driving errors like the following when attempting to fetch a user's passport from ECM:

Caused by: java.lang.NoSuchMethodError: 'org.springframework.http.HttpStatus org.springframework.http.ResponseEntity.getStatusCode()'
        at bio.terra.externalcreds.client.ApiClient.invokeAPI(ApiClient.java:500)
        at bio.terra.externalcreds.api.OidcApi.getProviderPassportWithHttpInfo(OidcApi.java:314)